storage:
  build: .
  volumes:
    - /data
    - /usr/share/elasticsearch/data
    - /usr/share/elasticsearch/config
redis:
  image: redis
  command: "redis-server /data/redis.conf"
  volumes_from:
    - storage
  ports:
    - "6379:6379"
elasticsearch:
  image: "elasticsearch:1.4"
  volumes_from:
    - storage
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  image: "logstash:1.4.2"
  command: "logstash -f /data/logstash.conf"
  volumes_from:
    - storage
  links:
    - elasticsearch
    - redis
  ports:
    - "5000:5000"
kibana4:
  image: digitalwonderland/kibana
  links:
    - elasticsearch
  ports: 
    - "5601:5601"
nginx:
  image: nginx
  command: "nginx -c /data/nginx.conf -g 'daemon off;'"
  links:
    - kibana4
  ports:
    - "80:80"
  volumes_from:
    - storage
