storage:
  build: .
  volumes:
    - /data
beaver:
  image: "ombitron/docker-beaver"
  environment:
    BEAVER_OPTS: "-c /data/beaver.conf"
  volumes_from:
    - storage
  volumes:
    - /var/lib/docker/containers:/var/lib/docker/containers
