storage:
  image: busybox
  volumes:
    - /data
influxdb:
  image: "tutum/influxdb"
  environment:
    PRE_CREATE_DB: "shinken;collectd"
  volumes_from:
    - storage
  volumes:
    - influxdb/config.toml:/config/config.toml
  ports:
    - "8083:8083"
    - "8086:8086" 
collectdproxy:
  image: "falzm/docker-influxdb-collectd-proxy"
  ports:
    - "8096:8096/udp" 
  environment:
    ICP_HOST: "influxdb:8086"
    ICP_DATABASE: "collectd"
    ICP_USERNAME: "root"
    ICP_PASSWORD: "root"
    ICP_NORMALIZE: "true"
    ICP_VERBOSE: "false"
  links:
    - influxdb
grafana:
  image: "tutum/grafana"
  links:
    - influxdb
  ports:
    - "80:80"
  environment:
    INFLUXDB_HOST: "influxdb"
    INFLUXDB_PORT: "8086"
    INFLUXDB_NAME: "collectd"
    INFLUXDB_USER: "root"
    INFLUXDB_PASS: "root"
    INFLUXDB_IS_GRAFANA: "true"
shinken:
  #image: "roblayton/shinken"
  build: . 
  links:
    - influxdb
    - collectdproxy
  ports:
    - "7767:7767" 
    - "7768:7768" 
