storage:
  image: busybox
  volumes:
    - /data
influxdb:
  image: "tutum/influxdb:0.8.8"
  environment:
    PRE_CREATE_DB: "shinken;collectd"
  volumes_from:
    - storage
  volumes:
    - influxdb/config.toml:/config/config.toml
  ports:
    - "8083:8083"
    - "8086:8086" 
    - "8090:8090" 
collectdproxy:
  image: "falzm/docker-influxdb-collectd-proxy"
  ports:
    - "8096:8096/udp" 
  environment:
    ICP_HOST: "influxdb:8086"
    ICP_DATABASE: "collectd"
    ICP_USERNAME: "root"
    ICP_PASSWORD: "root"
    ICP_NORMALIZE: "true"
    ICP_VERBOSE: "false"
  links:
    - influxdb
grafana:
  image: "grafana/grafana:2.0.2"
  links:
    - influxdb
  ports:
    - "3000:3000"
shinken:
  #image: "roblayton/shinken"
  build: . 
  links:
    - influxdb
    - collectdproxy
  ports:
    - "7767:7767" 
    - "7768:7768" 
